steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- powershell: |
    npm install -g yarn
    npm install -g vsce
    yarn install
    yarn run compile
    yarn run package
    yarn run package-offline-windows
    yarn run package-offline-osx
    yarn run package-offline-osx-arm64
  displayName: 'Installing Dependencies and build packages'
