trigger: none
pr:
  - master
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'
- task: CmdLine@2
  displayName: 'Installing Dependencies'
  inputs:
    script: |
      sudo npm install -g yarn
- task: CmdLine@2
  displayName: 'Building Vsix Packages'
  inputs:
    script: |
      yarn install
      yarn run compile
      yarn run package